######################################################
################# Setup Stenographer #################
######################################################
---
- name: Install Stenographer package
  yum:
    name: stenographer
    state: installed

-
  name: Set stenographer config
  when: (steno_monifs == "")
  template:
    src: templates/stenographer-config.j2
    dest: "/etc/stenographer/config.{{ item.1 }}"
  with_indexed_items: "{{ rock_monifs }}"

-
  name: Set stenographer config
  when: (steno_monifs != "")
  template:
    src: templates/stenographer-config.j2
    dest: "/etc/stenographer/config.{{ item.1 }}"
  with_indexed_items: "{{ steno_monifs }}"


- name: Create Stenographer Rock directory
  file:
    path: "{{ stenographer_rock_dir }}"
    state: directory
    mode: 0644
    owner: root
    group: root

- name: Copy Stenographer information file
  copy:
    src: "templates/stenoread.info"
    dest: "{{ stenographer_rock_dir }}/stenoread.info"
    mode: 0644
    owner: root
    group: root

- name: Create Stenographer directories
  file:
    path: "{{ stenographer_data_dir }}"
    mode: 0755
    owner: "{{ stenographer_user }}"
    group: "{{ stenographer_group }}"
    state: directory

- name: Install stenographer service files
  copy:
    src: "templates/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - stenographer.service
    - stenographer@.service

- name: Generate stenographer keys
  command: >
    /usr/bin/stenokeys.sh {{ stenographer_user }} {{ stenographer_group }}
  args:
    creates: /etc/stenographer/certs/client_key.pem

- name: Configure Stenographer service
  service:
    name: stenographer
    enabled: yes
    state: started

- name: Configure Stenographer per-interface
  systemd:
    name: "stenographer@{{ item }}"
    enabled: yes
    state: started
    daemon_reload: yes
  with_items: "{{ rock_monifs }}"
